name:                CardEngine
version:             0.1.0.0
github:              "githubuser/CardEngine"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/CardEngine#readme>

dependencies:
- base >= 4.7 && < 5
- text
- extra
- edit-distance
- directory
- filepath
- data-clist
- extra
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  CardEngine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CardEngine
    - base
    - text
    - extra
    - edit-distance
    - directory
    - filepath
    - data-clist
    - optparse-applicative

tests:
  CardEngine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CardEngine
